version = "v0.4.1.4-d.1.3.2"
predictor_type = "hgb-c"
base_dir = "/home/mroe734/Documents/srs/AI-risk-score/"

[model_parameters]
dir = "config/clinical/HGBc/"
subfolders = [ "labels", "imbalance", "hyperparameters", "calibrator" ]
name = "ai_risk_HGBc_"
extension = ".toml"

[io_parameters]
dir = "models/clinical/"
name = "ai_risk_HGBc-"
extension = ".pkl"

[fig_parameters]
dir = "figures/clinical/"
name = "ai_risk_HGBc_"
extension = ".png"

[data_parameters]
dir = "config/clinical/data/"
subfolders = [ "general", "features", "splitting", "preprocessing" ]
name = "ai_risk_data_"
extension = ".toml"
