DROP TABLE IF EXISTS ai_risk_data;
CREATE TABLE ai_risk_data AS SELECT AGE, ETHNICITY_ORIGINAL, SEX_ORIGINAL, DEP18_ORIGINAL, M3_SCORE, PRIOR_CANCER, FACILITY, ADMISSION_ACUITY, CATEGORY_LEVEL_1, OP_SEVERITY, OP_CODE, DOMICILE_CODE, TRAUMA, MORTALITY_30D, ANY_COMP FROM all_data;

SELECT * FROM ai_risk_data;