[labels]
label_list = [
  "MORTALITY_30D",
  "MORTALITY_90D",
  "MORTALITY_1Y",
  "READMIT_ACUTE_30D",
  "READMIT_ACUTE_90D",
  "ANY_COMP",
  "SHOCK",
  "RESPIRATORY_FAILURE",
  "SEPSIS",
  "STROKE",
  "AKI",
  "CARDIAC_ARRHYTHMIA",
  "DELIRIUM",
  "GI_BLEEDING",
  "HAEMORRHAGE",
  "IMPLANT_GRAFT",
  "MYOCARDIAL_EVENT",
  "PNEUMONIA",
  "SSI",
  "UTI",
  "VTE",
]
