version = "v0.2.1-c2"
model_type = "hgb"
base_dir = "/home/mroe734/Documents/srs/AI-risk-score/"

[model_parameters]
dir = "config/HGB/"
name = "ai_risk_HGB-"
extension = ".toml"

[io_parameters]
dir = "models/"
name = "ai_risk_HGB-"
extension = ".pkl"

[data_parameters]
dir = "config/data/"
name = "ai_risk_data-"
extension = ".toml"
