version = "v0.0.1"

[config_parameters]
learning_rate = 0.1
loss = "log_loss"
l2_regularization = 0.5
max_features = 0.2

[io_parameters]
dir = "/home/mroe734/Documents/srs/AI-risk-score/models/"
name = "HGB_"
extension = ".pkl"

[data_parameters]
dir = "/home/mroe734/Documents/srs/AI-risk-score/config/"
name = "AI_risk_data_config"
extension = ".toml"
