log_path = "/home/mroe734/Documents/srs/AI-risk-score/logs"
log_message = "Exception raised in "
print_message = "An exception was raised. Check logs "
unexpected_message = "An unexpected error occurred. Check logs "
