#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
constants.py

Constants for the clinical paper.
"""

COLOUR_MAP = {
    "MORTALITY_30D": "#33367A",
    "MORTALITY_90D": "#33367A",
    "MORTALITY_1Y": "#33367A",
    "READMIT_ACUTE_30D": "#96690E",
    "READMIT_ACUTE_90D": "#96690E",
    "ANY_COMP": "#96690E",
    "SSI": "#2D90D8",
    "VTE": "#2D90D8",
    "SEPSIS": "#2D90D8",
    "RESPIRATORY_FAILURE": "#2D90D8",
    "SHOCK": "#2D90D8",
    "STROKE": "#2D90D8",
    "AKI": "#2D90D8",
    "CARDIAC_ARRHYTHMIA": "#2D90D8",
    "DELIRIUM": "#2D90D8",
    "GI_BLEEDING": "#2D90D8",
    "HAEMORRHAGE": "#2D90D8",
    "IMPLANT_GRAFT": "#2D90D8",
    "MYOCARDIAL_EVENT": "#2D90D8",
    "PNEUMONIA": "#2D90D8",
    "UTI": "#2D90D8",
}
LABEL_MAP = {
    "MORTALITY_30D": "30-day mortality",
    "MORTALITY_90D": "90-day mortality",
    "MORTALITY_1Y": "1-year mortality",
    "READMIT_ACUTE_30D": "30-day acute readmission",
    "READMIT_ACUTE_90D": "90-day acute readmission",
    "ANY_COMP": "Any complications",
    "SSI": "SSI",
    "VTE": "VTE",
    "SEPSIS": "Sepsis",
    "RESPIRATORY_FAILURE": "Respiratory failure",
    "SHOCK": "Shock",
    "STROKE": "Stroke",
    "AKI": "AKI",
    "CARDIAC_ARRHYTHMIA": "Cardiac arrhythmia",
    "DELIRIUM": "Delirium",
    "GI_BLEEDING": "GI bleeding",
    "HAEMORRHAGE": "Haemorrhage",
    "IMPLANT_GRAFT": "Implant / graft complications",
    "MYOCARDIAL_EVENT": "Myocardial event",
    "PNEUMONIA": "Pneumonia",
    "UTI": "UTI",
}
MODEL_MAP = {
    "MORTALITY_30D": "calibrator",
    "MORTALITY_90D": "predictor",
    "MORTALITY_1Y": "calibrator",
    "READMIT_ACUTE_30D": "predictor",
    "READMIT_ACUTE_90D": "predictor",
    "ANY_COMP": "predictor",
    "SSI": "predictor",
    "VTE": "predictor",
    "SEPSIS": "predictor",
    "RESPIRATORY_FAILURE": "calibrator",
    "SHOCK": "predictor",
    "STROKE": "calibrator",
    "AKI": "predictor",
    "CARDIAC_ARRHYTHMIA": "predictor",
    "DELIRIUM": "predictor",
    "GI_BLEEDING": "predictor",
    "HAEMORRHAGE": "calibrator",
    "IMPLANT_GRAFT": "predictor",
    "MYOCARDIAL_EVENT": "predictor",
    "PNEUMONIA": "predictor",
    "UTI": "calibrator",
}
