[hyperparameters]
loss_name = "BCEWithLogitsLoss"
optim_name = "Adam"
epochs = 50
batch_size = 64
lr = 0.001

## Note in_features are automatically identified during model creation

[architecture]
[[architecture.layers]]
type = "Linear"
out_features = 50

[[architecture.layers]]
type = "BatchNorm1d"

[[architecture.layers]]
type = "ReLU"

[[architecture.layers]]
type = "Linear"
out_features = 1

[[architecture.layers]]
type = "BatchNorm1d"

[[architecture.layers]]
type = "ReLU"
